allowBuilds:
  bufferutil: false
  esbuild: set this to true or false
  keccak: set this to true or false
  sharp: true
  unrs-resolver: true
  utf-8-validate: false
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
